FROM node:trixie-slim

WORKDIR /app

COPY  ./package.json ./

RUN npm install

COPY ./ ./

RUN npm install --save-dev jest @testing-library/react @testing-library/jest-dom babel-jest @babel/preset-env @babel/preset-react jest-environment-jsdom

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
