name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f Dockerfile.dev -t crisroller/react-dev .

      - name: Run tests in Docker
        run: docker run -e CI=true crisroller/react-dev npm run test